### ISSUE TITLE
Relationships should accept nil

### ISSUE THREAD

**Issue by jozefvaclavik** [LedgerSync/ledger_sync#61]
**Describe the bug**
Right now we specify our resource as
```
module LedgerSync
  class Expense < LedgerSync::Resource
    attribute :currency, type: Type::String
    attribute :amount, type: Type::Integer
    attribute :memo, type: Type::String
    attribute :payment_type, type: Type::String
    attribute :transaction_date, type: Type::Date
    attribute :exchange_rate, type: Type::Float

    references_one :vendor, to: Vendor
    references_one :account, to: Account

    references_many :line_items, to: ExpenseLineItem

    def name
      "Purchase: #{amount} #{currency}"
    end
  end
end
```

**To Reproduce**
1. Edit `spec/integration/quickbooks_online/expenses/find_spec.rb`
2. Replace `resource` to be the minimum we require (just `ledger_id`)
```
let(:resource) do
  LedgerSync::Expense.new(expense_resource({ledger_id: '123'}))
end
```
3. run `bundle exec rspec spec/integrations/quickbooks_online/expenses/find_spec.rb`

```
  1) quickbooks_online/expenses/find #perform
     Failure/Error:
       raise ResourceError::AttributeTypeError.new(
         attribute: attribute,
         resource: self,
         value: val
       )

     LedgerSync::ResourceError::AttributeTypeError:
       Attribute account for LedgerSync::Expense should be a class supported by LedgerSync::Type::ReferenceOne.  Given: NilClass
     # ./lib/ledger_sync/resource_attribute/mixin.rb:30:in `block (2 levels) in _define_attribute_methods'
     # ./lib/ledger_sync/resource_attribute/mixin.rb:71:in `public_send'
     # ./lib/ledger_sync/resource_attribute/mixin.rb:71:in `assign_attribute'
     # ./lib/ledger_sync/resource_attribute/mixin.rb:76:in `block in assign_attributes'
     # ./lib/ledger_sync/resource_attribute/mixin.rb:75:in `each'
     # ./lib/ledger_sync/resource_attribute/mixin.rb:75:in `assign_attributes'
     # ./lib/ledger_sync/resource_attribute/mixin.rb:63:in `initialize'
     # ./lib/ledger_sync/resource.rb:37:in `initialize'
     # ./spec/integrations/quickbooks_online/expenses/find_spec.rb:33:in `new'
     # ./spec/integrations/quickbooks_online/expenses/find_spec.rb:33:in `block (2 levels) in <top (required)>'
     # ./spec/integrations/quickbooks_online/expenses/find_spec.rb:39:in `block (2 levels) in <top (required)>'
     # ./spec/integrations/quickbooks_online/expenses/find_spec.rb:44:in `block (3 levels) in <top (required)>'
     # ./spec/integrations/quickbooks_online/expenses/find_spec.rb:45:in `block (3 levels) in <top (required)>'
```

**Expected behavior**
Relationships should be optional to build the resource.

**Comment by jozefvaclavik** [comment]
Oh, just littlebit more context. This is more an issue of passing `nil` as a relationship. 

`LedgerSync::Expense.new({ledger_id: '123'})` works fine, but `LedgerSync::Expense.new({ledger_id: '123', account: nil})` crashes.

**Comment by mattgmarcus** [comment]
@ryanwjackson I think this should be in 1.1.1. Seems like an issue. You agree?

**Comment by ryanwjackson** [comment]
I'm find with 1.1.1.

**Comment by ryanwjackson** [comment]
Cannot reproduce.
